<?php try {

    /* @var $this TriggeredMessaging_DigitalDataLayer_Block_Ddl */
    $triggered_messaging_digital_data_layer_enabled = Mage::getStoreConfig('triggered_messaging/triggered_messaging_digital_data_layer_enabled');
	$triggered_messaging_digital_data_layer_prod_list_limit = Mage::getStoreConfig('triggered_messaging/triggered_messaging_digital_data_layer_prod_list_exposure');
	if($triggered_messaging_digital_data_layer_prod_list_limit===''){
		//If blank we want to expose all products, so set to a number the counter won't ever get to
		$triggered_messaging_digital_data_layer_prod_list_limit = -1;
	} else {
		//Else make sure it's an integer value so counter will hit the value
		$triggered_messaging_digital_data_layer_prod_list_limit = (int)$triggered_messaging_digital_data_layer_prod_list_limit;
	}

    // extract variable only when digital data layer is enabled
    if ($triggered_messaging_digital_data_layer_enabled == 1) :

        $observer = 'digital_data_layer_main/page_observer';
        $mage = Mage::getSingleton($observer);

        $page = $mage->getPage();
        if (isset($page['category']) &&
            isset($page['category']['pageType'])
        ) {
            switch ($page['category']['pageType']) {
                case 'category':
                case 'search':
                case 'tag':
                    break;
                default:
                    return;
            }
        }

        // Grab product list data (from category and search pages)
        $that = Mage::getBlockSingleton('catalog/product_list');
        if (!$that) return;
	// Check to see if we are on the advanced search page
	if ($this->getRequest()->getControllerName()=='advanced') {
		// If we are on the advanced search index page, don't build item collection				
		if(strrpos(Mage::app()->getRequest()->getActionName(), 'result') === false){
			return;
		}
		// If were not on the index, assume we are on the result page, build collection from results
		$_productCollection = Mage::getSingleton('catalogsearch/advanced')->getProductCollection();    
	} else {
		// If were not on the advanced search page, get loaded products
		$_productCollection = $that->getLoadedProductCollection();
	}
        if (!$_productCollection) return;
        if ($_productCollection->count() === 0) return;

        // Extract products displayed on category page
        // Need to do it after content block as the specified products are loaded then
        $products = array();
		$counter = 0;
        foreach ($_productCollection as $_product) {
			if($counter===$triggered_messaging_digital_data_layer_prod_list_limit){
				//Once limit has been hit, break out of the loop
				break;
			} else {
				$counter++;
			}
            array_push($products, $mage->_getProductModel($_product, 'list'));
        }

        $preloaded_product = $mage->getProduct();
        ?>
        <!-- W3C Digital Data Layer Extra Info Start -->
        <script type="text/javascript">
            try {
                <?php if ($products) : ?>
                <?php if (!$preloaded_product) : ?>
                window.digitalData.product = <?php echo json_encode($products) ?>;
                <?php else : ?>
                window.digitalData.product.push.apply(window.digitalData.product, <?php echo json_encode($products) ?>);
                <?php endif; ?>
                <?php endif; ?>
            } catch (e) {
            }
        </script>
        <!-- W3C Digital Data Layer Extra Info End -->
    <?php
    endif;

} catch (Exception $e) {
} ?>
